### PR TITLE
Update to net46

### PR DESCRIPTION
**Pull request by danmoseley**
.NET 4.5 has been out of support for 6 years and the targeting pack is no longer available. The repo can only be built by those who happen to already have it. I don't..

 .NET 4.6 is the latest version potentially in support. https://learn.microsoft.com/en-US/lifecycle/faq/dotnet-framework

1. Change to target .NET 4.6
2. Remove custom Array.Empty as it's in .NET 4.6.
3. Future proof defines with _OR_GREATER.
4. Fix the dotnet.exe finder tests. DOTNET_ROOT is not guaranteed to be defined. The defaults are documented, use those otherwise. 

All tests pass locally.

### CODE REVIEW

**Comment by danmoseley** [comment]
I see this project is in maintenance mode. Neverthless I suggest to take this change, because currently the repo cannot be built by some people.

**Comment by natemcmaster** [comment]
Thanks for making a PR to keep things up to date. I don’t see any problem with moving forward to a modern version of .NET Framework. 

Out of curiosity, can you elaborate on the problem? I was under the impression that the targeting packs could be installed via NuGet, which is enabled in this project here: https://github.com/natemcmaster/CommandLineUtils/blob/dd5de0698dee24dca38d4496069bd5a31662d80f/Directory.Build.props#L58

**Comment by danmoseley** [comment]
IIRC, it simply would not build within VS, I was directed to get the targeting pack, then discovered it has been removed from downloads. I didn't look further.

**Comment by danmoseley** [comment]
Do you want to merge (if only to get it out of my active PR list 🙂)

**Comment by natemcmaster** [comment]
Thanks @danmoseley !

**Pull request merged**
