### PR TITLE
Show allowed values in help text for Nullable/ValueTuple<bool,T> option/argument

### PR DESCRIPTION
**Pull request by scott-xu**
Fix https://github.com/natemcmaster/CommandLineUtils/issues/388

### CODE REVIEW

**Comment by scott-xu** [comment]
Fix https://github.com/natemcmaster/CommandLineUtils/issues/388

**Comment by scott-xu** [comment]
@natemcmaster 
If the option type is `Nullable<T>`, should we return `CommandOptionType.SingleOrNoValue` if T is `CommandOptionType.SingleValue`
https://github.com/natemcmaster/CommandLineUtils/blob/main/src/CommandLineUtils/Internal/CommandOptionTypeMapper.cs#L63

**Comment by scott-xu** [comment]
> @natemcmaster
> If the option type is `Nullable<T>`, should we return `CommandOptionType.SingleOrNoValue` if T is `CommandOptionType.SingleValue`
> https://github.com/natemcmaster/CommandLineUtils/blob/main/src/CommandLineUtils/Internal/CommandOptionTypeMapper.cs#L63

I ask because I have to specify `CommandOptionType.SingleOrNoValue`. Otherwise, the help text would be
```
  -enumOpt3|--verb3 <VERB3>         nullable enum option desc.
                                    Allowed values are: None, Normal, Extreme.
```
rather than
```
  -enumOpt3|--verb3[:<VERB3>]       nullable enum option desc.
                                    Allowed values are: None, Normal, Extreme.
```
https://github.com/natemcmaster/CommandLineUtils/blob/b10e80222377889c3244e23a7c18a338551114ad/test/CommandLineUtils.Tests/DefaultHelpTextGeneratorTests.cs#L208-L209

**Review by natemcmaster — APPROVED** [review]
Looks good to me! There is a merge conflict now, though, with your other PR. Can you resolved and update?

**Comment by natemcmaster** [comment]
re: your question
>  If the option type is Nullable<T>, should we return CommandOptionType.SingleOrNoValue if T is CommandOptionType.SingleValue

Let's open a separate issue for this. We need to think through backwards compatibility of this change given that the current behavior is SingleValue. I think changing to SingleOrNoValue could break some users unless we also improve the parser to support `--a value` for SingleOrNoValue.

**Comment by scott-xu** [comment]
Conflicts are resolved. 
Issue https://github.com/natemcmaster/CommandLineUtils/issues/394 is created.

**Comment by natemcmaster** [comment]
Thanks @scott-xu !

**Pull request merged**
