### PR TITLE
Improve code readability by improving the signal to noise ratio. 

### PR DESCRIPTION
**Pull request by kbilsted**
We remove around 1300 lines of code which is approximately 6,6% of the total lines of code consisting of excessive empty lines, empty comments, and short meaningles comments.
The stuff you get annoyed about when you speed-read code.

When we read code, we use techniques ranging from _scanning_ (fast-pased reading), to 
slow-pased _scrutiny_. 

              (code reading spectrum)
 
         fast                        slow 
       <---------------------------------->
    Scannning                     Scrutinizing

When discussing code readability, it often from the perspective slower-pased reading. 
I believe we do a great deal of _scanning_ when we read code. Much more than what is given credit. 
My belief is rooted in a lot of facts

  * Only source code is typeset with Mono-spaced fonts. Books, magazines , newspapers, etc. all use proportional fonts
  * Most programmers have an opinion and preference with regards to indentation size. The Linux kernel coding style serving one of the largest public code bases insist on indents being 8 characters to improve readability
  * 99.999% of programmer prefer using syntax highlighting and colors when working in editors/IDE's. 
  * 99.999% of code samples in programming blogs or Q/A sites like StackOverflow use syntax highligting and colors
  * People express difficulty in keeping concentration and focus when faced with code bases with large portions of text, that do not contribute meaning.

With this PR cleaning the code we impact code readability when _scanning_ code.

              (Scannning)
         
       ---------------------------- o ------>
       Impact

and much less so for when we are _scrutinizing_

              (scrutinizing)
         
       ---- o ------------------------------>
       Impact

### CODE REVIEW

**Comment by kbilsted** [comment]
There are build errors due to a rule enforcing documentation. Does that rule make sense given the amount of documentation that do not provide value?

**Comment by natemcmaster** [comment]
How did you create these changes? Manually? IDE? Console tool?

**Comment by kbilsted** [comment]
A tool https://github.com/kbilsted/WhitespaceWarrior and then a reviewed before each comit. It was less than 5 comments that survived the review.

it could be interesting to look for even longer "meaningless" comments but I wanted you to see the value in it before I spent more time

**Comment by natemcmaster** [comment]
I'm not sold on this change. I think the benefit is marginal. In some cases, the changes in this PR remove important lines of code. For example, removing `#region` usage from the docs/ folder breaks the documentation generation because DocFX uses regions to extract snippets of code. I'm also wary of requiring contributors (and myself) to use a new tool to reformat code whenever new changes are added. Single-line XML doc blocks is not the default in Visual Studio. I prefer to keep the code base consistently formatted and formatted using Visual Studio's default settings (exceptions granted for settings which can be configured by .editorconfig).

**Pull request closed without merging**
