### PR TITLE
Support netstandard1.6

### PR DESCRIPTION
**Pull request by couven92**
Without any code changes, I was able to target .NET Standard 1.6 which makes CLU available on more .NET platforms.

### CODE REVIEW

**Comment by couven92** [comment]
Fixes #5

**Comment by natemcmaster** [comment]
If you wanted to support netstandard1.3, you could use this as a replacement for AppContext.GetData. It's ugly, but it works.

```c#
        public static string GetDataFromAppDomain(string propertyName)
        {
            var appDomainType = typeof(object).GetTypeInfo().Assembly?.GetType("System.AppDomain");
            var currentDomain = appDomainType?.GetProperty("CurrentDomain")?.GetValue(null);
            var deps = appDomainType?.GetMethod("GetData")?.Invoke(currentDomain, new[] { propertyName });

            return deps as string;
        }
```

In netstandard2.0, though, I'd rather still with AppContext.GetData.

**Comment by natemcmaster** [comment]
I would be happy to take this if you keep the netstandard2.0 tfm, per discussion on #5. Also, can you retarget this PR to the `dev` branch?

**Comment by couven92** [comment]
@natemcmaster There you go! :)

**Comment by natemcmaster** [comment]
Thanks @couven92. I'll get a 2.0.1 update on nuget.org soon.

**Pull request merged**
